version: 2
updates:
  - package-ecosystem: "dotnet-sdk"
    directory: "/dotnet/cluster_management"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "dotnet-sdk"
    directory: "/dotnet/npgsql"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "gomod"
    directory: "/go/cluster_management"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "gomod"
    directory: "/go/pgx"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "maven"
    directory: "/java/cluster_management"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "maven"
    directory: "/java/liquibase"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/java/pgjdbc"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "gradle"
    directory: "/java/spring_boot"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/javascript/cluster_management"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/javascript/node-postgres"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/javascript/postgres-js"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/lambda"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/python/asyncpg"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/python/cluster_management"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/python/psycopg"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/python/psycopg2"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/python/sqlalchemy"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "cargo"
    directory: "/rust/cluster_management"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "cargo"
    directory: "/rust/sqlx"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/typescript/prisma"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/typescript/sequelize"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/typescript/type-orm"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "gitleaks/gitleaks-action"
