name: JavaScript node-postgres integration tests

permissions: {}

on:
  push:
    branches: [ main ]
    paths:
      - 'javascript/node-postgres/**'
      - '.github/workflows/javascript-node-postgres-integ-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'javascript/node-postgres/**'
      - '.github/workflows/javascript-node-postgres-integ-tests.yml'
  workflow_dispatch:

jobs:
  create-cluster:
    uses: ./.github/workflows/dsql-cluster-create.yml
    with:
      workflow_name: javascript-node-postgres
    secrets:
      AWS_IAM_ROLE: ${{ secrets.JAVASCRIPT_IAM_ROLE }}
    permissions:
      id-token: write # required by aws-actions/configure-aws-credentials

  node-postgres-integ-test:
    needs: create-cluster
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required by aws-actions/configure-aws-credentials

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: '18.x'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ secrets.JAVASCRIPT_IAM_ROLE }}
        aws-region: ${{ needs.create-cluster.outputs.region }}

    - name: Configure and run integration for nodejs HowTo
      working-directory: ./javascript/node-postgres
      env:
        CLUSTER_ENDPOINT: ${{ needs.create-cluster.outputs.cluster-endpoint }}
        REGION: ${{ needs.create-cluster.outputs.region }}
        CLUSTER_USER: 'admin'
      run: |
        npm ci
        npm test

  delete-cluster:
    if: always() && needs.create-cluster.result == 'success'
    needs: [create-cluster, node-postgres-integ-test]
    uses: ./.github/workflows/dsql-cluster-delete.yml
    with:
      cluster-id: ${{ needs.create-cluster.outputs.cluster-id }}
      region: ${{ needs.create-cluster.outputs.region }}
    secrets:
      AWS_IAM_ROLE: ${{ secrets.JAVASCRIPT_IAM_ROLE }}
    permissions:
      id-token: write # required by aws-actions/configure-aws-credentials
